### ISSUE TITLE
Imagen no se muestra correctamente

### ISSUE THREAD

**Issue by L30nardoSV** [CPAR-INICTEL/CPAR_GPUs#3]
En https://github.com/CPAR-INICTEL/CPAR_GPUs/blob/main/clase_0.ipynb, la imagen `git_loc.png` no se muestra correctamente.

**Comment by Luciana-cloud** [comment]
esto lo cambiaste verdad? Ahora se visualiza todo

**Comment by L30nardoSV** [comment]
> esto lo cambiaste verdad? Ahora se visualiza todo

No cambie esa parte. De todas maneras, ahora si se visualiza.
